maintainer       "Facet Digital, LLC"
maintainer_email "info@facetdigital.com"
license          "Apache 2.0"
description      "Monkey-patches Chef to help avoid CHEF-3694 warnings."
version          "1.0"
